- name: update apt
  ansible.builtin.apt:
    state: present
    update_cache: true
    pkg:
      - ca-certificates
      - curl
      - gnupg
      - apt-transport-https

- name: get gpg keyring
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /usr/share/keyrings/docker.asc

- name: install gpg keyring
  ansible.builtin.lineinfile:
    path: /etc/apt/sources.list.d/docker.list
    line: deb [arch=amd64 signed-by=/usr/share/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    create: true

- name: install docker
  ansible.builtin.apt:
    update_cache: true
    state: present
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin

- name: enable docker
  ansible.builtin.service:
    name: docker
    enabled: true
